[package]
name = "ghaction_version_gen"
description = "Generate various version options as github action outputs"
version = "0.12.0"
authors = ["Leandro Lisboa Penz <lpenz@lpenz.org>"]
edition = "2021"
license = "MIT"
readme = "README.md"
repository = "https://github.com/lpenz/ghaction-version-gen"
categories = ["command-line-utilities"]
keywords = ["github-action", "version-generate"]

[dependencies]
clap = { version = "4.0.27", features = ["derive"] }
regex = "1.7.0"
anyhow = "1.0.66"
toml = "0.5.9"

[dev-dependencies]
tempfile = "3.3.0"
